server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/gateway_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret: VmVyeVNlY3JldEtleUZvckp3dERvbnRTaGFyZVRoaXMxMjM0NTY3ODkw
  expiration: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
